fastlane_version '1.96.0'

default_platform :ios

platform :ios do
  def nuget(sln)
    sh "nuget restore #{sln} -verbosity detailed"
  end

  desc 'Release build with clean'
  lane :release_build do
    xamarin_build(
        solution: '/Users/user/projects/buildAgent/work/1/Pro.sln',
        platform: 'iPhone',
        target: 'Clean',
        project: 'subproject1,subproject2,subproject3',
        build_type: 'Release',
        print_all: true
    )

    xamarin_build(
        solution: '/Users/user/projects/buildAgent/work/1/Pro.sln',
        platform: 'iPhone',
        target: 'Build',
        build_type: 'Release',
        print_all: false
    )

  end

  desc 'Build xamarin project for debug and start nuunit tests'
  lane :run_ui_tests do |options|
    nuget(options[:sln])

    xamarin_build(
      solution: options[:sln],
      platform: 'iPhoneSimulator',
      build_type: 'Debug',
      target: 'Clean',
      print_all: true
    )
    sh "nunit-console #{options[:dll_file]}"
  end

  desc 'Build xamarin release for iPhone with setting custom certificates and provision derived from match'
  lane :release_custom_cert do |options|

    provision_uuid = "ef857752-5177-4399-bf2e-1c889b4386a0"

    # certificate from provision
    cert = extract_certificate(
      uuid: provision_uuid,
      log_certificate: false
    )

    subject = Hash[cert.subject.to_a.map {|arr|  [arr[0], arr[1]]}]
    name = subject['CN']

    ENV['FL_XAMARIN_UPDATE_CONFIGURATION_XAMARIN_PROJECT'] = options[:csproj]
    ENV['FL_XAMARIN_UPDATE_CONFIGURATION_TARGET'] = 'Release'
    ENV['FL_XAMARIN_UPDATE_CONFIGURATION_PLATFORM'] = 'iPhone'

    [
      ['CodesignProvision', provision_uuid],
      ['CodesignKey', name]
    ].each do |kv|
      xamarin_update_configuration(
        property: kv[0],
        value: kv[1]
      )
    end

    xamarin_build(
      solution: options[:sln],
      platform: 'iPhone',
      target: 'Clean',
      build_type: 'Release',
      print_all: false
    )
  end
end
